export const InputTypes = {
  TEXT: "text",
  PASSWORD: "password",
  SUBMIT: "submit",
  RESET: "reset",
  RADIO: "radio",
  CHECKBOX: "checkbox",
  BUTTON: "button",
  FILE: "file",
  IMAGE: "image",
  DATE: "date",
  DATETIME_LOCAL: "datetime-local",
  EMAIL: "email",
  MONTH: "month",
  NUMBER: "number",
  URL: "url",
  WEEK: "week",
  SEARCH: "search",
  TEL: "tel",
};